server:
  port: ${PORT:8080}

spring:
  application:
    name: taskmanager

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/taskmanager}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:170105}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update

app:
  cors-origin: ${CORS_ORIGIN:http://localhost:5173}